### ISSUE TITLE
Where are the binary files supposed to be

### ISSUE THREAD

**Issue by juchom** [microsoft/infersharpaction#31]
Hello,

I've juste tested the github actions with this piece of code

```yaml
      - name: Run Infer#
        uses: microsoft/infersharpaction@v0.2
        id: runinfersharp
        with:
          binary-path: ${{ env.PUBLISH_WEBSITE }}
      - name: Infer# analysis results
        run: echo "${{ steps.runinfersharp.outputs.results }}"
        
      - name: Zip Website
        run: pushd ${{ env.PUBLISH_WEBSITE }}; zip -r ${{ env.PUBLISH_WEBSITE_ZIP }} .; popd
```

Where `${{ env.PUBLISH_WEBSITE }}` equals to :

```yaml
    env:
      BUILD_CONFIGURATION: Release
      PUBLISH_WEBSITE: ${{ github.workspace }}/artifacts/Website
```

Looking at the logs I have this error :

```console
cp: cannot stat '/home/runner/work/MyWebsite/MyWebsite/artifacts/Website': No such file or directory
Timed out methods: 0
Unknown instructions:
```

I'm sure the dlls are here and the directory exists because this is the pipeline I use to deploy my webapp.

Have I missed something from the doc ?

**Comment by xinshiMSFT** [comment]
I think the error may come from this step of the action: https://github.com/microsoft/infersharpaction/blob/618f2c5c1f79dd1986e2136d1f57f2b7f1733e5f/entrypoint.sh#L5
where $1 is the binary path you provided, which contains the binary files.

I am not sure why it complains about this non-existent folder if the same pipeline has been working for you, but I have a working sample that may help you identify the issue:
```
jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build ConsoleApp1/ConsoleApp1.sln
    
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v0.2
      id: runinfersharp
      with:
        binary-path: 'ConsoleApp1/ConsoleApp1/bin'
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
```
I have a console app located at the root of the repo, called "ConsoleApp1". The script builds it with "dotnet build". The binary files would be created in "ConsoleApp1/ConsoleApp1/bin", which is supplied as the value for _binary-path_. The full path to the .dll file is "/home/runner/work/githubactions/githubactions/ConsoleApp1/ConsoleApp1/bin/Debug/netcoreapp2.2/ConsoleApp1.dll", where _githubactions_ is my repo name (I assume your repo name is MyWebsite?). By setting _binary-path_ as "ConsoleApp1/ConsoleApp1/bin", it copies everything under this folder for the analysis later.

Hopefully it would be helpful to you. Please let me know if you are still having issues.

**Comment by juchom** [comment]
Thanks for your reply, but it doesn't work. I've modified my pipeline like this :

```yaml
      - name: List files before infersharp
        run: ls -R ${{ env.PUBLISH_WEBSITE }}
      - name: Run Infer#
        uses: microsoft/infersharpaction@v0.2
        id: runinfersharp
        with:
          binary-path: ${{ env.PUBLISH_WEBSITE }}
```

The `ls -R ${{ env.PUBLISH_WEBSITE }}` shows the dll are here :

```console
Run ls -R /home/runner/work/MyWebsite/MyWebsite/artifacts/Website
/home/runner/work/MyWebsite/MyWebsite/artifacts/Website:
Azure.Core.dll
Azure.Identity.dll
Azure.Security.KeyVault.Certificates.dll
Azure.Security.KeyVault.Secrets.dll
Markdig.dll
Microsoft.AspNetCore.Authentication.JwtBearer.dll
Microsoft.AspNetCore.Authentication.OpenIdConnect.dll
Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.dll
Microsoft.AspNetCore.Razor.Language.dll
```
