### ISSUE TITLE
Unable to get job output

### ISSUE THREAD

**Issue by omer-za** [microsoft/infersharpaction#41]
I tried 
```
            - name: Run Infer#
              id: runinfersharp
              uses: microsoft/infersharpaction@v1.2
              with:
                  binary-path: .
            - name: Write Infer# analysis results
              run: echo "${{join(steps.runinfersharp.outputs.*, '\n')}}" >> report.txt
```
Doesn't works

**Comment by xinshiMSFT** [comment]
Can you please share the output log from the step "Run Infer#"?

**Comment by Kazpers** [comment]
@xinshiMSFT 

I seem to have the same issue. I really cannot paste the entire output log of the Run Infer# step as it's org private stuff, but the step runs fine and identifies 21 issues:

Run microsoft/infersharpaction@v1.2
  with:
    binary-path: ./src/xxx/infer
  env:
    SRC_DIRECTORY: ./src/xxx
    DOTNET_ROOT: /home/runner/.dotnet
/usr/bin/docker run --name e284909ddbd624d4d74ac7b2cefe6afdbc8ed4_12cf67 --label e28490 --workdir /github/workspace --rm -e SRC_DIRECTORY -e DOTNET_ROOT -e INPUT_BINARY-PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/xxx/xxx":"/github/workspace" e28490:9ddbd624d4d74ac7b2cefe6afdbc8ed4  "./src/xxx/infer"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1232  100  1232    0     0   5730      0 --:--:-- --:--:-- --:--:--  5730
Processing {./src/xxx/infer}
Copy binaries to a staging folder...

Coverage Statistics:

Method successfully translated: 12256 (93%)
Method partially translated: 959 (7%)
Instructions translated: 206569 (60%)
Instructions skipped: 138051 (40%)
======================================

Translation completed. Analyzing...

[...]

Found 21 issues (console output truncated to 5, see '/github/workspace/infer-out/report.txt' for the full list)
                        Issue Type(ISSUED_TYPE_ID): #
                Null Dereference(NULL_DEREFERENCE): 14
  Thread Safety Violation(THREAD_SAFETY_VIOLATION): 7

[...]

Found 21 issues
                        Issue Type(ISSUED_TYPE_ID): #
                Null Dereference(NULL_DEREFERENCE): 14
  Thread Safety Violation(THREAD_SAFETY_VIOLATION): 7

**Comment by xinshiMSFT** [comment]
@Kazpers Can you elaborate a bit more on the issue you are facing here? It looks like that the analysis completed successfully. Is `[...]` literally what showed up in the build log?

**Comment by omer-za** [comment]
I also get a report with various of issues but I can't access to file `github/workspace/infer-out/report.txt`
I tried upload it as an artifact right after that analysis step and also tried to get job output, none of them get you the raw output into a file. I can only read the results through the GitHub action web console.

**Comment by Kazpers** [comment]
@xinshiMSFT The problem is that I get an empty string from steps.runinfersharp.outputs.results (and like the original post no output at all from attempting echo "${{join(steps.runinfersharp.outputs.*, '\n')}}" )

So the analysis runs fine, but the outputs/result is not populated. This makes it tricky to pick up the results with other actions to make them more visible than just in the log.

**Comment by xinshiMSFT** [comment]
Actually, while investigating another thing, I figured that using relative path would get you the raw report file. The change I did earlier was kind of redundant. For example:
```
    - name: Run Infer#
      uses: microsoft/infersharpaction@v1.2
      with:
        binary-path: 'Examples'

    - name: Upload Infer# report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: infer-out/report.txt
```
I will update the README in the near future.

**Comment by veikkoeeva** [comment]
I add here that I seem to have an issue with the SARIF file. The step is available at https://github.com/lumoin/Verifiable/runs/4539220635?check_suite_focus=true#step:19:34, the problem is that I don't know where to find the SARIF file. Currently it's pointing at ` ${{ github.workspace }}/infer-out/report.sarif`.

It appears also that `infer-out/report.txt` wasn't enough in my case (or maybe I missed something?), but the text file is found at `${{ github.workspace }}/infer-out/report.txt`.

**Comment by omer-za** [comment]
Thanks for the fast handling, I got the report using 
```
    - name: Upload Infer# report
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: infer-out/report.txt
```
